[package]
name = "blaze-pk"
version = "0.4.8"
edition = "2021"
description = "Rust library for Blaze packet system"
license = "MIT"
authors = ["Jacobtread <jacobtread@gmail.com>"]
repository = "https://github.com/jacobtread/BlazePK-rs"
readme = "README.md"
keywords = ["EA", "serialization", "packet"]
categories = ["network-programming", "parser-implementations"]

[badges]
# Move to passively-maintained
maintenance = { status = "experimental" }

[dependencies]
tokio = { version = "1", features = ["full"], optional = true }
blaze-ssl-async = { version = "0.1.1", optional = true }

[features]
default = ["sync", "async", "blaze-ssl"]
# Syncronous reading / writing functions
sync = []
# Async reading / writing functions
async = ["tokio"]
# Blaze-ssl reading / writing functions
blaze-ssl = ["async", "dep:blaze-ssl-async"]